project:
  type: website
  output-dir: docs
  pre-render: "Rscript generate-player-pages.R"

format:
  html:
    theme: cosmo

website:
  title: "Bowling Stats"
  navbar:
    left:
      - text: "Leaderboard"
        href: index.qmd
      - text: "Sessions"
        href: sessions.qmd
      - text: "Anatolii"
        href: players/anatolii.qmd
      - text: "Daniel"
        href: players/daniel.qmd
      - text: "Flora"
        href: players/flora.qmd
      - text: "Julia"
        href: players/julia.qmd
      - text: "Maria"
        href: players/maria.qmd
      - text: "Niko"
        href: players/niko.qmd
